AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  UploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SmartMontageUpload
      Handler: app.handler
      Runtime: python3.9
      CodeUri: .
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          UPLOAD_BUCKET: smart-montage-uploads
      Policies:
        - S3WritePolicy:
            BucketName: smart-montage-uploads
      Events:
        UploadApi:
          Type: Api
          Properties:
            Path: /upload
            Method: post
